name: Run PR Install Script

on:
  pull_request:
    branches:
      - main
    paths:
      - "install/*.sh"

jobs:
  run-install-script:
    runs-on: ubuntu-latest
    container:
      image: debian:latest
    
    steps:
      - name: Install GitHub CLI
        run: |
          # Install GitHub CLI
          apt update
          apt install -y git gh
          
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0  # Fetch full commit history
      - name: Add Git safe directory
        run: |
          git config --global --add safe.directory /__w/ProxmoxVE/ProxmoxVE
      
      - name: Set up GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "GH_TOKEN=${GH_TOKEN}" >> $GITHUB_ENV
      - name: Get changed files in PR
        id: changed-files
        run: |
          # Use GitHub CLI to get the list of changed files in the PR
          CHANGED_FILES=$(gh pr diff --name-only ${{ github.event.pull_request.number }})
          echo "Changed files: $CHANGED_FILES"
          # Set CHANGED_FILE as an environment variable in the correct format
          echo "SCRIPT=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Check if install script is changed
        id: check-install-script
        run: |
          if echo "${{ env.SCRIPT }}" | grep -q '^install/.*-install.sh$'; then
            echo "Install script found!"
          else
            echo "No install script found."
            exit 1
          fi

      - name: Replace $FUNCTION_FILE_PATH
        run: |
          sed -i 's|source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"|source <(curl -s https://raw.githubusercontent.com/michelroegl-brunner/ProxmoxVE/refs/heads/main/misc/pr-install.func)|' ${{ env.SCRIPT }}
      - name: Make script executable
        run: chmod +x ${{ env.SCRIPT }}

      - name: Install curl
        run: apt update && apt install -y curl
        
      - name: Run install script and capture error message
        id: run-install
        run: |
          set +e  # Allow the command to fail
          echo "Running install script..."
          echo "Checking if the script exists: ls -l ${{ env.CHANGED_FILE }}"  # Debugging output
          ERROR_MSG=$(./${{ env.CHANGED_FILE }} 2>&1)  # Capture both stdout and stderr
          echo "$ERROR_MSG" # Save error message to a file for later use
          exit_code=$?  # Capture the exit code
          echo "exit_code=$exit_code" >> $GITHUB_ENV
          echo "ERROR_MSG=$ERROR_MSG" >> $GITHUB_ENV
          set -e  # Restore exit-on-error

      - name: Post error comment if install script fails
        if: env.exit_code != '0'  # This step will only run if previous steps fail
        run: |
          # Post an error comment to the pull request with the captured error message
          echo "Posting error message as a comment..."
          gh pr comment ${{ github.event.pull_request.number }} \
            --body "Error: The install script failed with the following message:\n\n${{ env.ERROR_MSG }}"
